### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by nvladimus** [AllenNeuralDynamics/exa-spim-control#61]
Hi, everyone,
I wanted to run the code in simulated mode, but the installation didn't succeed. I created a clean conda env (python 3.7) and tried to install there following the instructions, but `pip install -e .` failed due to `permission denied` issues:
![image](https://github.com/user-attachments/assets/acceab60-548d-4138-86c6-04f150072334)

I also tried to install the `spim-core` manually, but that also failed:
![image](https://github.com/user-attachments/assets/ee7ea793-1b32-488e-b16e-5712d3252774)

Is this a config issue, or some repositories remain private? Or am I doing something dumb?
Many thanks!
Nikita

**Comment by aliddell** [comment]
@nvladimus have you associated your SSH key with your GitHub account? If you don't want to do that it might be better to change the repos in the [dependencies ](https://github.com/AllenNeuralDynamics/exa-spim-control/blob/main/pyproject.toml#L25) to use HTTPS rather than SSH. Both of them are public, so that shouldn't be the problem.

So you could try changing lines 25-26 in pyproject.toml to

```
    "tigerasi @ git+https://github.com/AllenNeuralDynamics/TigerASI.git@main#egg=TigerASI",
    "spim_core @ git+https://github.com/AllenNeuralDynamics/spim-core.git@main#egg=spim_core",
```

It almost worked for me. But here's what I get:

```
ERROR: Cannot install exaspim and exaspim==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    exaspim 0.1.0 depends on tigerasi 0.0.26 (from git+https://github.com/AllenNeuralDynamics/TigerASI.git@main#egg=TigerASI)
    spim-core 0.1.0 depends on tigerasi 0.0.26 (from git+ssh://****@github.com/AllenNeuralDynamics/TigerASI.git@main#egg=TigerASI)
```

exaspim wants https and spim-core wants ssh. So what I'd suggest is to generate an SSH key pair and associate it with your GitHub account. Then it should work for you. Note for the maintainers, all those URLs in the pyproject.toml files for each project could change to https and avoid issues like this in the future.

**Comment by nvladimus** [comment]
Many thanks, I will try that!

**Comment by adamkglaser** [comment]
Hey @nvladimus. Apologies for the troubles, this repository has not been updated in quite some time. It is also inactive, we have been working on new repositories over the last 6+ months with new acquisition software. It would be best to dive into these if helpful/useful. Documentation and commenting in the code is scarce but coming soon to hopefully make it more usable by others.

Hardware driver repo that will construct a microscope from a configuration YAML file + classes for data writing
https://github.com/AllenNeuralDynamics/voxel/tree/main

GUI repo that builds upon the generated instrument object
https://github.com/AllenNeuralDynamics/view

ExA-SPIM specific repo that uses both of the above
https://github.com/AllenNeuralDynamics/exaspim-control

**Comment by nvladimus** [comment]
Thanks, looks very cool! It wasn't obvious that there are `exa-spim-control` vs `exaspim-control` repos =)
